"""
Brainstorm structuring tools for the Feature Brainstorm Agent.

Provides a helper to convert a free-form feature description + Q&A context
into a well-structured GitHub Issue body following the EventVerse DDD template.
"""

from typing import Optional


# ---------------------------------------------------------------------------
# DDD Layer choices
# ---------------------------------------------------------------------------

DDD_LAYERS = [
    "Domain",
    "Application",
    "Presentation",
    "Infrastructure",
    "Cross-cutting",
]

KMP_PLATFORMS = ["Android", "iOS", "Desktop", "Web", "Server"]


# ---------------------------------------------------------------------------
# Tool
# ---------------------------------------------------------------------------

def structure_feature_as_issue(
    feature_title: str,
    user_story: str,
    description: str,
    acceptance_criteria: list[str],
    ddd_domain: str,
    ddd_layer: str,
    suggested_use_cases: list[str],
    suggested_entities_or_value_objects: list[str],
    platform_targets: list[str],
    priority: str,
    technical_notes: Optional[str] = None,
    estimation: Optional[str] = None,
) -> str:
    """Converts structured feature information into a GitHub Issue body (Markdown).

    Call this tool AFTER collecting all necessary information from the user
    through the brainstorm conversation.

    Args:
        feature_title: Short, clear feature name.
        user_story: User story in 'As a X, I want Y so that Z' format.
        description: Full description of the feature.
        acceptance_criteria: List of acceptance criteria strings (without checkbox prefix).
        ddd_domain: The DDD domain this feature belongs to (e.g. 'Event', 'Ticket', 'User').
        ddd_layer: One of: Domain, Application, Presentation, Infrastructure, Cross-cutting.
        suggested_use_cases: List of suggested Use Case class names (e.g. ['PublishEventUseCase']).
        suggested_entities_or_value_objects: List of entity/value object names (e.g. ['EventTitle', 'EventStatus']).
        platform_targets: List of platforms from: Android, iOS, Desktop, Web, Server.
        priority: One of: High, Medium, Low.
        technical_notes: Optional technical implementation notes or considerations.
        estimation: Optional story point or time estimation (e.g. '3 story points', '2 days').

    Returns:
        A fully formatted GitHub Issue body string in Markdown.
    """
    # Acceptance criteria checkboxes
    ac_lines = "\n".join(f"- [ ] {ac}" for ac in acceptance_criteria)

    # Platform checkboxes
    all_platforms = KMP_PLATFORMS
    platform_lines = "\n".join(
        f"- [x] {p}" if p in platform_targets else f"- [ ] {p}"
        for p in all_platforms
    )

    # DDD Use Cases
    use_cases_str = (
        ", ".join(f"`{uc}`" for uc in suggested_use_cases)
        if suggested_use_cases
        else "_none identified yet_"
    )

    # DDD Entities/Value Objects
    entities_str = (
        ", ".join(f"`{e}`" for e in suggested_entities_or_value_objects)
        if suggested_entities_or_value_objects
        else "_none identified yet_"
    )

    # Technical notes section
    tech_section = (
        f"\n### 🔧 Technical Notes\n{technical_notes}\n"
        if technical_notes
        else ""
    )

    # Estimation section
    est_section = (
        f"\n### ⏱️ Estimation\n{estimation}\n"
        if estimation
        else ""
    )

    body = f"""\
## 🎯 Feature: {feature_title}

### 📖 User Story
{user_story}

### 📝 Description
{description}

### ✅ Acceptance Criteria
{ac_lines}

### 🏗️ DDD Context
| Field | Value |
|---|---|
| **Domain** | `{ddd_domain}` |
| **Layer** | `{ddd_layer}` |
| **Suggested Use Cases** | {use_cases_str} |
| **Entities / Value Objects** | {entities_str} |

### 📱 Platform Target
{platform_lines}

### 🚦 Priority
**{priority}**
{tech_section}{est_section}
---
_Generated by EventVerse Feature Brainstorm Agent_ 🤖
"""
    return body
