package com.eventverse.app.routes

/**
 * **Utang gerbang RBAC** (B5, 2026-09-29): route tenant yang **tidak** menolak pengguna tanpa wewenang
 * modul. Diisi dari probe pertama (218 route; 65 menolak dengan benar).
 *
 * Aturan ratchet (`RouteGateTest`):
 * - route baru yang tidak menolak dan tidak ada di sini → **merah** (gerbang wajib sejak hari pertama);
 * - route di sini yang kini menolak → **merah** sampai barisnya dihapus (utang hanya boleh berkurang).
 *
 * Kosongkan daftar ini per modul: tambahkan `requireModuleAccess` (tulis: fail-closed) **sebelum** body dibaca.
 */
internal object RouteGateLedger {

    /** Terbuka untuk setiap anggota tenant **dengan sengaja** — dibutuhkan setiap layar untuk menyusun menu. */
    val openByDesign: Set<String> = setOf(
        "GET /api/tenant/info",
        "GET /api/tenant/entitlement"
    )

    val ungated: Set<String> = setOf(
        "DELETE /api/tenant/process-catalog/{processId}",
        "DELETE /api/tenant/production/work-orders/{id}/lines/{lineName}",
        "DELETE /api/tenant/sampling/orders/{id}/flow",
        "DELETE /api/tenant/tech-pack/{id}",
        "GET /api/tenant/billing-preview",
        "GET /api/tenant/customization-requests",
        "GET /api/tenant/departments/archived",
        "GET /api/tenant/departments/{id}",
        "GET /api/tenant/fulfillment/route-settings",
        "GET /api/tenant/fulfillment/transfers",
        "GET /api/tenant/module-assignments",
        "GET /api/tenant/pipeline",
        "GET /api/tenant/pipeline/modules",
        "GET /api/tenant/process-catalog",
        "GET /api/tenant/process-catalog/phase-tags",
        "GET /api/tenant/production/work-orders",
        "GET /api/tenant/production/work-orders/telemetry",
        "GET /api/tenant/production/work-orders/{id}",
        "GET /api/tenant/roles",
        "GET /api/tenant/roles/{id}",
        "GET /api/tenant/sampling/orders",
        "GET /api/tenant/sampling/orders/{id}",
        "GET /api/tenant/sampling/orders/{id}/flow",
        "GET /api/tenant/sampling/orders/{id}/flow-legs",
        "GET /api/tenant/sampling/orders/{id}/storage",
        "GET /api/tenant/stage-flow",
        "GET /api/tenant/stage-templates",
        "GET /api/tenant/tech-pack",
        "GET /api/tenant/tech-pack/by-style/{styleCode}/latest-released",
        "GET /api/tenant/tech-pack/by-style/{styleCode}/versions",
        "GET /api/tenant/tech-pack/{id}",
        "GET /api/tenant/tech-pack/{id}/explosion",
        "GET /api/tenant/traceability/codes/{code}",
        "GET /api/tenant/traceability/work-orders/{kind}/{id}/allocation",
        "GET /api/tenant/traceability/work-orders/{kind}/{id}/containers",
        "GET /api/tenant/traceability/work-orders/{kind}/{id}/labels.pdf",
        "GET /api/tenant/traceability/work-orders/{kind}/{id}/reconciliation",
        "GET /api/tenant/traceability/work-orders/{kind}/{id}/spk-card.pdf",
        "GET /api/tenant/traceability/work-orders/{kind}/{id}/worksheet.pdf",
        "GET /api/tenant/transfers/manifests",
        "GET /api/tenant/transfers/manifests/{id}",
        "GET /api/tenant/work-queue/board",
        "GET /api/tenant/work-queue/washing/batches",
        "GET /api/tenant/work-queue/washing/pending-bundles",
        "PATCH /api/tenant/process-catalog/{processId}",
        "PATCH /api/tenant/sampling/orders/{id}/milestones/{step}",
        "POST /api/tenant/customization-requests",
        "POST /api/tenant/process-catalog",
        "POST /api/tenant/production/work-orders/launch-from-deal",
        "POST /api/tenant/production/work-orders/{id}/lines",
        "POST /api/tenant/production/work-orders/{id}/progress",
        "POST /api/tenant/sampling/orders",
        "POST /api/tenant/sampling/orders/{id}/approve",
        "POST /api/tenant/sampling/orders/{id}/finishing/deposits",
        "POST /api/tenant/sampling/orders/{id}/finishing/vendor",
        "POST /api/tenant/sampling/orders/{id}/finishing/vendor-receive",
        "POST /api/tenant/sampling/orders/{id}/qc/inspect",
        "POST /api/tenant/sampling/orders/{id}/release",
        "POST /api/tenant/sampling/orders/{id}/revision",
        "POST /api/tenant/sampling/orders/{id}/rework",
        "POST /api/tenant/sampling/orders/{id}/stage",
        "POST /api/tenant/sampling/orders/{id}/store",
        "POST /api/tenant/sampling/orders/{id}/work/release",
        "POST /api/tenant/sampling/orders/{id}/work/start",
        "POST /api/tenant/tech-pack/blank",
        "POST /api/tenant/tech-pack/from-sampling",
        "POST /api/tenant/tech-pack/{id}/release",
        "POST /api/tenant/tech-pack/{id}/resolve-materials",
        "POST /api/tenant/tech-pack/{id}/revise",
        "POST /api/tenant/traceability/codes/{code}/open",
        "POST /api/tenant/traceability/codes/{code}/tally",
        "POST /api/tenant/traceability/sacks/{code}/close",
        "POST /api/tenant/traceability/work-orders/{kind}/{id}/print-ticket",
        "POST /api/tenant/transfers/manifests/customer-dispatch",
        "POST /api/tenant/transfers/manifests/internal",
        "POST /api/tenant/transfers/manifests/makloon-outbound",
        "POST /api/tenant/transfers/manifests/{id}/receive",
        "POST /api/tenant/work-queue/cards/initialize",
        "POST /api/tenant/work-queue/cards/output",
        "POST /api/tenant/work-queue/merge-gate/close",
        "POST /api/tenant/work-queue/rework/issue",
        "POST /api/tenant/work-queue/rework/{id}/advance",
        "POST /api/tenant/work-queue/washing/batches",
        "POST /api/tenant/work-queue/washing/batches/{id}/complete-sort",
        "PUT /api/tenant/process-catalog/phase-tags",
        "PUT /api/tenant/sampling/orders/{id}",
        "PUT /api/tenant/sampling/orders/{id}/flow",
        "PUT /api/tenant/sampling/orders/{id}/flow/phase-tags",
        "PUT /api/tenant/sampling/orders/{id}/technical-spec",
        "PUT /api/tenant/tech-pack/{id}/bom",
        "PUT /api/tenant/tech-pack/{id}/labor",
        "PUT /api/tenant/tech-pack/{id}/size-yield",
    )
}
