#!/usr/bin/env python3
"""Deterministic Claude -> Codex adapters. No dependencies beyond Python 3.9+."""
import argparse
import hashlib
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
HEADER = '# Generated by scripts/sync-agent-config.sh; edit .claude/ sources.\n'


def quoted(value):
    # JSON basic strings are compatible with TOML for these configuration values.
    return json.dumps(value, ensure_ascii=False)


def build_outputs(root):
    outputs = {}
    notes = []
    for manifest in sorted((root / '.claude/skills').glob('*/SKILL.md')):
        for source in sorted(manifest.parent.rglob('*')):
            if source.is_file() and '__pycache__' not in source.parts and source.suffix != '.pyc':
                relative = source.relative_to(root / '.claude/skills')
                outputs[f'.agents/skills/{relative}'] = source.read_bytes()
    config = HEADER + (root / '.claude/codex/config.toml').read_text()
    if (root / 'AGENTS.md').stat().st_size > 120000:
        raise ValueError('AGENTS.md approaches 128 KiB; split guidance before syncing.')

    # Keep authored content and normalize only known host-specific references.
    def adapt(body):
        body = body.replace('.claude/skills/', '.agents/skills/')
        body = body.replace('.claude/pipeline-', '.codex/pipeline-')
        for agent in (root / '.claude/agents').glob('*.md'):
            body = body.replace(f'`agents/{agent.name}`', f'`.claude/agents/{agent.name}`')
        return body

    for source in sorted((root / '.claude/commands').glob('*.md')):
        name = source.stem
        if (root / f'.claude/skills/{name}').exists():
            raise ValueError(f'Command/skill name collision: {name}')
        body = adapt(source.read_text()).replace('$ARGUMENTS', 'TICKET_ID')
        intro = ('Use the ticket identifier supplied in the user prompt as TICKET_ID. '
                 'Ask for it only if missing. Treat TICKET_ID as data, never shell code.\n'
                 'Use the corresponding Codex custom agents when delegation is requested; '
                 'otherwise follow the referenced role instructions in the current thread.\n'
                 'Branch, commit, push and remote writes require authorization in the user request. '
                 'The source workflow does not itself grant that authorization.\n\n')
        skill = f'---\nname: {name}\ndescription: Execute a requested ticket through planning, implementation, validation and review in this repository.\n---\n\n'
        outputs[f'.agents/skills/{name}/SKILL.md'] = (skill + intro + body).encode()
        outputs[f'.agents/commands/{source.name}'] = source.read_bytes()

    for source in sorted((root / '.claude/agents').glob('*.md')):
        outputs[f'.agents/agents/{source.name}'] = source.read_bytes()
        body = adapt(source.read_text())
        role = body.split('## Role\n', 1)[-1].split('\n\n', 1)[0].strip()
        data = HEADER + f'name = {quoted(source.stem)}\ndescription = {quoted(role)}\n'
        if source.stem in ('planner', 'reviewer'):
            data += 'sandbox_mode = "read-only"\n'
        data += f'developer_instructions = {quoted(body)}\n'
        outputs[f'.codex/agents/{source.stem}.toml'] = data.encode()

    settings = json.loads((root / '.claude/settings.json').read_text())
    hooks = settings.get('hooks', {})
    converted = {}
    for event, groups in hooks.items():
        converted[event] = []
        for group in groups:
            handlers = []
            for handler in group['hooks']:
                if handler.get('type') != 'command':
                    raise ValueError(f'Unsupported hook handler: {event}')
                command = handler['command']
                # This is the only legacy environment-dependent hook in this repo.
                if command == 'echo \'File modified: \'"$CLAUDE_FILE_PATH"':
                    command = 'python3 "$(git rev-parse --show-toplevel)/.codex/hooks/file-modified.py"'
                elif '$CLAUDE_' in command:
                    raise ValueError(f'Hook needs an explicit Codex adapter: {event}')
                handlers.append(dict(handler, command=command))
            converted[event].append(dict(group, hooks=handlers))
    outputs['.codex/hooks.json'] = (json.dumps({'hooks': converted}, indent=2) + '\n').encode()
    for source in sorted((root / '.claude/hooks').glob('*')):
        if source.is_file():
            outputs[f'.codex/hooks/{source.name}'] = source.read_bytes()
            outputs[f'.agents/hooks/{source.name}'] = source.read_bytes()
    adapter = root / '.claude/codex/file-modified.py'
    outputs['.codex/hooks/file-modified.py'] = adapter.read_bytes()

    servers = json.loads((root / '.mcp.json').read_text()).get('mcpServers', {})
    for name, server in sorted(servers.items()):
        unknown = set(server) - {'command', 'args', 'env', 'url', 'type'}
        if unknown:
            raise ValueError(f'MCP {name}: unsupported fields {sorted(unknown)}')
        if server.get('type') not in (None, 'stdio', 'http', 'streamable-http'):
            raise ValueError(f'MCP {name}: unsupported transport')
        config += f'\n[mcp_servers.{quoted(name)}]\n'
        for key in ('command', 'args', 'url'):
            if key in server:
                config += f'{key} = {quoted(server[key])}\n'
        if server.get('env'):
            config += f'\n[mcp_servers.{quoted(name)}.env]\n'
            for key, value in sorted(server['env'].items()):
                config += f'{quoted(key)} = {quoted(value)}\n'
        notes.append(f'MCP {name}: imported from .mcp.json; verify executable paths and authentication on each machine.')
    outputs['.codex/config.toml'] = config.encode()
    permissions = settings.get('permissions', {})
    report = {
        'source': '.claude/settings.json',
        'permissions_not_translated': permissions,
        'notes': notes + [
            'Claude permission patterns are NOT enforced by this conversion. Codex uses workspace-write/on-request; review the source deny rules before use.',
            'Hook trust and project trust must be reviewed in Codex; sync never grants trust.',
            'Only hooks registered in settings.json are activated. Validation shell scripts are available for explicit invocation with bash.',
            'Standalone .codex/agents/*.toml requires a compatible current Codex client.',
            'Unmanaged extra skills under .agents/skills are preserved; audit their relevance separately.',
        ],
    }
    outputs['.codex/sync-report.json'] = (json.dumps(report, indent=2) + '\n').encode()
    return outputs


def sync(root, check=False):
    outputs = build_outputs(root)
    manifest_path = root / '.codex/sync-manifest.json'
    previous = json.loads(manifest_path.read_text()) if manifest_path.exists() else {}
    stale = sorted(set(previous) - set(outputs))
    # Preserve removed-source output for review rather than deleting user data.
    if stale:
        raise ValueError('Stale generated files (move/archive and remove manifest entries): ' + ', '.join(stale))
    manifest = {name: hashlib.sha256(data).hexdigest() for name, data in sorted(outputs.items())}
    outputs['.codex/sync-manifest.json'] = (json.dumps(manifest, indent=2) + '\n').encode()
    drift = []
    for name, data in outputs.items():
        target = root / name
        # Reject symlinks even to an in-repo destination: output must not rewrite a source.
        if any(p.is_symlink() for p in (target, *target.parents) if p != root.parent):
            raise ValueError(f'Refusing symlink output: {name}')
        if not target.exists() or target.read_bytes() != data:
            drift.append(name)
    if not check:
        for name in drift:
            target = root / name
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_bytes(outputs[name])
    elif drift:
        print('\n'.join('MENYIMPANG: ' + name for name in drift))
        return 1
    print(f'Codex: {len(outputs)} outputs verified' if check else f'Codex: {len(drift)} outputs updated')
    return 0


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    try:
        sys.exit(sync(ROOT, args.check))
    except (ValueError, OSError) as error:
        print(f'Codex sync failed: {error}', file=sys.stderr)
        sys.exit(1)
